[workspace]
resolver = "2"
members = [
    "crates/spite-compiler",
    "crates/spitestack-cli",
    "crates/spitedb",
    "crates/spitedb-napi",
]
exclude = [
    "packages/examples/typescript/.spitestack",
]

[profile.release]
lto = true
